export default {
    mine_icon_hot: require("../assets/imgs/mine_icon_hot.png"),
    mine_icon_preview: require("../assets/imgs/mine_icon_preview.png"),
    mine_icon_manhua: require("../assets/imgs/mine_icon_manhua.png"),
    mine_icon_activity: require("../assets/imgs/mine_icon_activity.png"),
    mine_icon_nearby: require("../assets/imgs/mine_icon_nearby.png"),
    mine_icon_random: require("../assets/imgs/mine_icon_random.png"),
    mine_icon_feedback: require("../assets/imgs/mine_icon_feedback.png"),
    mine_icon_more: require("../assets/imgs/mine_icon_more.png"),
    default_header: require("../assets/imgs/default_header.png"),
    profile_level1: require("../assets/imgs/profile_level1.png"),
    arrow_right: require("../assets/imgs/arrow_right.png"),
    placeholder: require("../assets/imgs/placeholder.png"),

    publish_video: require("../assets/imgs/publish_video.png"),
    publish_picture: require("../assets/imgs/publish_picture.png"),
    publish_text: require("../assets/imgs/publish_text.png"),
    publish_audio: require("../assets/imgs/publish_audio.png"),
    publish_link: require("../assets/imgs/publish_link.png"),
    publish_review: require("../assets/imgs/publish_review.png"),
    back: require("../assets/imgs/back.png"),
    nav_game: require("../assets/imgs/nav_game.png"),
    nav_random: require("../assets/imgs/nav_random.png"),
    nav_coin: require("../assets/imgs/nav_coin.png"),
    nav_setting: require("../assets/imgs/nav_setting.png"),
    video_play: require("../assets/imgs/video_play.png"),
    gif_play: require("../assets/imgs/gif_play.png"),

}